stages:
    - prepare
    - build
    - test

variables:
    GIT_SUBMODULE_STRATEGY: normal

cellframe-node-schedule:
    stage: build
    tags:
    - cellframe-node
    script: ~/production/integration/gitlab-CI/build_all_handler.sh cellframe-node

trigger-dashboard:
    only:
     - support-4958
    variables:
      UPDATE: "true"
    trigger:
     project: cellframe/cellframe-dashboard
     branch: support-4958
