stages:
    - prepare
    - build
    - test

variables:
    GIT_SUBMODULE_STRATEGY: normal

cellframe-node-schedule:
    stage: build
    tags:
    - cellframe-node
    only:
    - master
    - /^release.*$/
    - /^pubtest.*$/
    script: ~/production/integration/gitlab-CI/build_all_handler.sh cellframe-node 

kelvin-node-test:
    stage: build
    tags:
    - cellframe-node
    except:
    - master
    - /^release.*$/
    - /^pubtest.*$/
    script: ~/production/integration/gitlab-CI/build_test_handler.sh cellframe-node 
