stages:
    - prepare
    - build
    - test

variables:
    GIT_SUBMODULE_STRATEGY: normal

docker prepare:
  stage: prepare
  variables:
    DOCKERFILES_DIR: "$CI_PROJECT_DIR/dockerfiles/linux/"
  rules:
    - if: $CI_COMMIT_REF_NAME == "support-4862"
    - changes:
      - $DOCKERFILES_DIR/*
  when: manual
  script:
    - docker build -f $DOCKERFILES_DIR/linuxbuild.Dockerfile -t localhost:5000/debian_prepared .
    - docker push localhost:5000/debian_prepared
    - docker image remove debian:stretch
    - docker image remove localhost:5000/debian_prepared
  tags:
    - docker
