stages:
    - prepare
    - build
    - test

variables:
    GIT_SUBMODULE_STRATEGY: normal

kelvin-node-schedule:
    stage: build
    tags:
    - cellframe-node
    script: ~/production/integration/gitlab-CI/build_all_handler.sh cellframe-node 
