sudo: required
language: c
compiler: gcc
dist: trusty
notifications:
  email: false

os:
  - linux
  - osx

before_install:
    - gcc -v
    - git submodule init
    - git submodule update --recursive

script:
    - export CC=gcc-5
    - mkdir build
    - cd build 
    - cmake -DBUILD_KELVIN_NODE_TESTS=ON ../
    - make
    - ctest --verbose

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - libev-dev
    - libmagic-dev



